name: ActivityPromotion
main: de.Chumper.ActivityPromotion.ActivityPromotion
version: 0.2
commands:
   ap:
      description: This is a command for all ActivityPromotion operations.
permissions:
    activitypromotion.reload:
        description: reload ActivityPromotion
        default: op
    activitypromotion.info:
        description: See Player informations
        default: op
    activitypromotion.loginmessage:
        description: Shows a message on login
        default: op